# Generated by Django 5.2.2 on 2025-07-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("contents", models.TextField(verbose_name="내용")),
                ("writer", models.CharField(max_length=200, verbose_name="작성자")),
                ("wdate", models.DateField(auto_now=True, verbose_name="작성일")),
                ("hit", models.IntegerField(verbose_name="조회수")),
            ],
        ),
    ]
